#!/usr/bin/env dash
if test -d .shrug
then
    echo "$0: error: .shrug already exists" 1>&2
else
    echo "Initialized empty shrug repository in .shrug"
    mkdir .shrug
    mkdir .shrug/index
    mkdir .shrug/commit
    mkdir .shrug/log
    # default branch: master
    echo 'master' >.shrug/.head
fi